services:
  discord-bot:
    image: node:20
    working_dir: /app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    volumes:
      - /docker/portainer/app:/app
    command: npm start
    restart: always
