services:
  pedro-bot:
    container_name: pedro-bot
    build: https://github.com/theepicsaxguy/Pedro-Bot.git#main
    volumes:
      - type: bind
        source: /var/log/pedro-bot
        target: /app/logs
      - type: bind
        source: /etc/pedro-bot
        target: /app/data
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}