services:
  pedro-bot:
    container_name: pedro-bot
    build:
      context: .
    volumes:
      - type: bind
        source: /var/log/pedro-bot
        target: /app/logs
      - type: bind
        source: /etc/pedro-bot
        target: /app/data
    restart: always
    pull_policy: build
    secrets:
      - discord_token
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - MONGO_URI=mongodb://mongodb:27017/pedro-bot
    depends_on:
      - mongodb
    networks:
      - pedro-network

  mongodb:
    container_name: pedro-bot-mongo
    image: mongo:8.0
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - pedro-network

volumes:
  mongo_data:

networks:
  pedro-network

secrets:
  discord_token:
    file: ./secrets/discord_token
