name: PR Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mongodb:
        image: mongo:8.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand("ping")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Check Prettier formatting
        run: npm run format:check
      - name: Security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
      - name: Run tests with coverage
        run: npm run test:ci
        env:
          DISCORD_TOKEN: "test-token-placeholder"
          CLIENT_ID: "123456789012345678"
          GUILD_ID: "123456789012345678"
          MONGO_URI: "mongodb://localhost:27017/pedro-bot-test"
          MATCHMAKING_CHANNEL: "matchmaking"
          NODE_ENV: "test"
      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
      - name: Validate Docker build
        run: docker build -t pedro-bot:test .
      - name: Test Docker container startup
        run: |
          docker run --rm -d \
            --name pedro-bot-test \
            -e DISCORD_TOKEN="test-token-placeholder" \
            -e CLIENT_ID="123456789012345678" \
            -e GUILD_ID="123456789012345678" \
            -e MONGO_URI="mongodb://host.docker.internal:27017/pedro-bot-test" \
            pedro-bot:test
          sleep 5
          if docker ps | grep -q pedro-bot-test; then
            echo "✅ Container started successfully"
            docker stop pedro-bot-test
          else
            echo "❌ Container failed to start"
            docker logs pedro-bot-test
            exit 1
          fi
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
  pr-title-check:
    name: PR Title Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
